"""Phase-1 quant trading platform core."""

from .backtest import BacktestEngine, BacktestResult
from .data import (
    generate_intraday_sample_bars,
    generate_sample_bars,
    generate_sample_market,
    load_akshare_futures_bars,
    load_bars_csv,
)
from .ctp import (
    CtpCallbackAdapter,
    CtpCallbackEvent,
    CtpConnectionConfig,
    CtpEventQueue,
    CtpLifecycleEvent,
    CtpFuturesGateway,
    CtpGatewayError,
    CtpMarketDataCallbackAdapter,
    CtpMarketDataSession,
    CtpOrderActionRequest,
    CtpOrderInsertRequest,
    CtpOrderInstruction,
    CtpRequestTimeoutError,
    CtpTradingSession,
    CtpTradingAccount,
    DryRunCtpMarketDataTransport,
    DryRunCtpTransport,
    NativeCtpMarketDataTransport,
    NativeCtpTraderTransport,
    ctp_depth_market_data_to_tick,
    futures_positions_from_ctp,
    order_from_ctp,
    split_order_for_ctp,
    tick_to_dict,
    trade_from_ctp,
)
from .datacenter import DataQualityReport, resample_bars, validate_bars
from .events import EventRecorder, RunEvent
from .execution import ExecutionConfig, SymbolExecutionConfig
from .futures import (
    CommissionRule,
    ContractRegistry,
    ContractSpec,
    FuturesFill,
    FuturesPosition,
)
from .models import Bar, Offset, Order, OrderType, Position, Side, Tick, Trade
from .optimization import GridSearchResult, run_grid_search
from .paper import PaperBrokerGateway, PaperTradingEngine, PaperTradingResult, run_paper_trading
from .replay import ReplayResult, run_market_replay
from .realtime import CtpRealtimeEngine, TickBarAggregator
from .risk import RiskConfig, RiskManager, SymbolRiskConfig
from .strategy import Strategy
from .trading_calendar import TradingCalendar, SessionTemplate, session_template
from .watchdog import CtpSessionWatchdog

__all__ = [
    "BacktestEngine",
    "BacktestResult",
    "Bar",
    "CtpCallbackAdapter",
    "CtpCallbackEvent",
    "CtpConnectionConfig",
    "CtpEventQueue",
    "CtpFuturesGateway",
    "CtpGatewayError",
    "CtpLifecycleEvent",
    "CtpMarketDataCallbackAdapter",
    "CtpMarketDataSession",
    "CtpOrderActionRequest",
    "CtpOrderInsertRequest",
    "CtpOrderInstruction",
    "CtpRequestTimeoutError",
    "CtpSessionWatchdog",
    "CtpTradingAccount",
    "CtpTradingSession",
    "DryRunCtpMarketDataTransport",
    "DryRunCtpTransport",
    "EventRecorder",
    "NativeCtpMarketDataTransport",
    "NativeCtpTraderTransport",
    "Order",
    "OrderType",
    "Offset",
    "CommissionRule",
    "ContractRegistry",
    "ContractSpec",
    "Position",
    "ExecutionConfig",
    "FuturesFill",
    "FuturesPosition",
    "GridSearchResult",
    "PaperBrokerGateway",
    "PaperTradingEngine",
    "PaperTradingResult",
    "Side",
    "ReplayResult",
    "RunEvent",
    "CtpRealtimeEngine",
    "TickBarAggregator",
    "RiskConfig",
    "RiskManager",
    "Strategy",
    "SymbolExecutionConfig",
    "SymbolRiskConfig",
    "Trade",
    "Tick",
    "generate_sample_bars",
    "generate_intraday_sample_bars",
    "generate_sample_market",
    "ctp_depth_market_data_to_tick",
    "futures_positions_from_ctp",
    "load_bars_csv",
    "load_akshare_futures_bars",
    "DataQualityReport",
    "SessionTemplate",
    "TradingCalendar",
    "order_from_ctp",
    "resample_bars",
    "run_market_replay",
    "run_paper_trading",
    "run_grid_search",
    "session_template",
    "split_order_for_ctp",
    "tick_to_dict",
    "trade_from_ctp",
    "validate_bars",
]
